# Generated by Django 6.0.2 on 2026-02-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='USER',
        ),
        migrations.AddField(
            model_name='review',
            name='USERS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
            preserve_default=False,
        ),
    ]
