# Generated by Django 5.2.11 on 2026-03-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_review_users_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tokens',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
