# Generated by Django 5.2.11 on 2026-03-06 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='USERS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
    ]
