# Generated by Django 5.2.11 on 2026-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_booking_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expected_time',
            field=models.TimeField(default='10:00:00'),
        ),
    ]
