# Generated by Django 5.2.11 on 2026-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking_expected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
